import type { Metadata } from "next";
import { IBM_Plex_Serif, Roboto } from "next/font/google";
import "./globals.css";
import { GeistSans } from "geist/font/sans";
import Navbar from "@/components/shared/Navbar";
import Hero from "@/components/shared/Hero";

const mons = Roboto({
	subsets: ["latin"],
	variable: "--font-roboto",
	weight: ["100","300","500","700","900"],
});



export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${mons.className} ${GeistSans.variable}`}
			>
				<Navbar/>
				<Hero/>
				{children}
			</body>
		</html>
	);
}
